### ISSUE TITLE
Install / usage instructions

### ISSUE THREAD

**Issue by pcj** [rustcoreutils/posixutils-rs#237]
Came to the repo from HN and was interested to try some of these out, but it's unclear how to install.

**Comment by jgarzik** [comment]
The rust standard `cargo install` should work.

**Comment by jgarzik** [comment]
Fixed in 6519e71bfb55ecd780baaff8ef22dd10ac801211

**Comment by pcj** [comment]
Thanks!  Nit add-on for a future PR, there is a misspelling `weclome`.
